language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DxGgbBu+9B6I2H8fqvIB4cMix8jcj0wz/1IuBrqinAyxL5n4MOk3cTw9evPRkXkQs6dXTNTiPm8qAFu6i8rUeRRUIBVYSj6vqOvSRNttZwiJyaAFhsGHXTnkCipOnbeeWyEAtmI2BG5u+rqH3hd7JGH2yxOVkHS8hHS62If5JAo9JlOGsHUI8z9Fu+kcWQEVSnX7dLylFEQ4cqoikE5dB/AJK9eIVWqnSWgpkUQwgMuDa2/UBhHzpwc6CDWmjQXW307NIVnqbeowRax76uhDyR62+8hgJ8z+NgjN8tVwfmHcacYZVj82iJtUQ3q+TihnVVmyq8R7oErr0HGYsDk5RO8yBw8k2vK8nk9HVUIWJ1Wy51Y4f1TUQ4ewYLBYHgp0jVZYXxxA5yKqLEfE019pmKlrfgOO7jYRdwR7u9aaJJcLr28HOSK04vUEukAoEGlHN4LoiDj4BI6FXtT9HfV57uHKzbDrs/cPO4/BVBqPKn/5CcPr5fwMLy8k+QTbCgqDmzyunNxzfjCwqTSumJGUYuEWMy9uagC/SyWQiUtiK7XqnEYONc0zUeQQwrZS6gzFeq/7ABWpX22hVuJBNpR26YqX29N5XtXFh2kQzNWOwh7y1K9zTWPTUUTfiF+g7YxO7MKgVXtSuXs/KbzaU0Kbv+G5oBji28B4oDhAKXW5m0o=
  app: justins-playground
  on:
    repo: Mrjustinfry/playground
